<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>了解报错信息</title>
	</head>
	<body>
		<script>
			// 1.常见的内置错误
						// Error:所有错误的父类型,
						// ReferenceError:引用变量不存在
						// TypeError:数据类型不正确的错误
						// RangeError:数据值不在其所允许的范围内
						// SyntaxError:语法错误
			
			
					// 1).ReferenceError:引用的变量不存在,
					// 例如:
					// 		console.log(a)  //ReferenceError: a is not defind
				
					// 2).TypeError:数据类型不正确的错误,
					// 例如:
					// 		let b    //声明一个变量没赋值
					// 		console.log(b.xxx)  //报错  TypeError: Cannot read property 'xxx' of undefined
					
					// 3).RangeError: 数据值不在其允许的范围内
					// 	function fn(){
					// 		fn()  //递归调用 
					// 	}
					// 	fn()   //RangeError: Maximum call stack size exceeded  超过了调用范围
						
					// 4).SyntaxError: 语法错误
					// 	const a = ''''  //SyntaxError: Unexpected string
					
				// 2.错误处理
				// 	捕获错误处理;try ... catch
						// 例:
							// try{
							// 	let d  
							// 	console.log(d.xxx)  
							// }catch(error){
							// 	console.log(error.message)  //提示文本
							// 	console.log(error.stack)  //提示文本及相关信息
							// }
						
					// 抛出错误: throw error
							function some(){   //抛出错误
								if(Date.now()%2 === 1){
									console.log('当前时间为基数可以执行')
								}else{
									throw new Error('当前时间为偶数无法执行')
								}
							}
					
							try{  //捕获错误
								some()
							}catch(error){
								alert(error.message)  //提示文本
							}
		</script>
	</body>
</html>
